USE Airport;

INSERT INTO [State]
VALUES 
('AZ', 'Arizona'),
('AR', 'Arkansas'),
('CA', 'California'),
('CO', 'Colorado'),
('CT', 'Connecticut'),
('DE', 'Delaware'),
('FL', 'Florida'),
('GA', 'Georgia'),
('HI', 'Hawaii'),
('ID', 'Idaho'),
('IL', 'Illinois'),
('IN', 'Indiana'),
('IA', 'Iowa'),
('KS', 'Kansas'),
('KY', 'Kentucky'),
('LA', 'Louisiana'),
('ME', 'Maine'),
('MD', 'Maryland'),
('MA', 'Massachusetts'),
('MI', 'Michigan'),
('MN', 'Minnesota'),
('MS', 'Mississippi'),
('MO', 'Missouri'),
('MT', 'Montana'),
('NE', 'New England'),
('NV', 'Nevada'),
('NH', 'New Hampshire'),
('NJ', 'New Jersey'),
('NM', 'New Mexico'),
('NY', 'New York'),
('NC', 'North Carolina'),
('ND', 'North Dakota'),
('OH', 'Ohio'),
('OK', 'Oklahoma'),
('OR', 'Oregon'),
('PA', 'Pennsylvania'),
('RI', 'Rhode Island'),
('SC', 'South Carolina'),
('SD', 'South Dakota'),
('TN', 'Tennessee'),
('TX', 'Texas'),
('UT', 'Utah'),
('VT', 'Vermont'),
('VA', 'Virginia'),
('WA', 'Washington'),
('WV', 'West Virginia'),
('WI', 'Wisconsin'),
('WY', 'Wyoming');


GO
INSERT INTO Airport (AirportID, AirportName, AirportCity, StateID, PassengersPerYear)
VALUES ('ATL', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta', 'GA', 50251962),
	('LAX', 'Los Angeles International Airport', 'Los Angeles', 'CA', 41232416),
	('ORD', '0''Hare International Airport', 'Chicago', 'IL', 38593028),
	('DFW', 'Dallas-Fort Worth International Airport', 'Dallas/Fort Worth', 'TX', 31861933),
	('DEN', 'Denver International Airport', 'Denver', 'CO', 29809091),
	('JFK', 'John F. Kennedy International Airport', 'New York', 'NY', 29533154),
	('SFO', 'San Francisco International Airport', 'San Francisco', 'CA', 26900016),
	('LAS', 'McCarran International Airport', 'Las Vegas', 'NV', 23364185),
	('SEA', 'Seattle-Tacoma International Airport', 'Seattle/Tacoma', 'WA', 22639120),
	('CLT', 'Charlotte-Douglas International Airport', 'Charlotte', 'NC', 22011225),
	('SAV', 'Savannah-Hilton Head International Airport', 'Savannah', 'GA', 1056265),
	('AGS', 'Augusta Regional Airport', 'Augusta', 'GA', 270797),
	('BHM', 'Birmingham-Shuttlesworth International Airport', 'Birmingham', 'AL', 1304467),
	('HSV', 'Huntsville International Airport', 'Huntsville', 'AL', 527801),
	('MOB', 'Mobile Regional Airport', 'Mobile', 'AL', 288209),
	('MGM', 'Montgomery Regional Airport', 'Montgomery', 'AL', 173210),
	('ANC', 'Ted Stevens Anchorage International Airport', 'Anchorage', 'AK', 2563524),
	('FAI', 'Fairbanks International Airport', 'Fairbanks', 'AK', 538881),
	('JNU', 'Juneau International Airport', 'Juneau', 'AK', 420442),
	('BET', 'Bethel Airport', 'Bethel', 'AK', 155791),
	('KTN', 'Ketchikan International Airport', 'Ketchikan', 'AK', 127881),
	('ENA', 'KENAI Municipal Airport', 'Kenai', 'AK', 92485),
	('SIT', 'Sitka Rocky Gutierrez Airport', 'Sitka', 'AK', 83404),
	('ADQ', 'Kodiak Airport', 'Kodiak', 'AK', 79682),
	('OTZ', 'Ralph Wien Memorial Airport', 'Kotzebue', 'AK', 64481),
	('OME', 'Nome Airport', 'Nome', 'AK', 60655),
	('SCC', 'Deadhorse Airport', 'Deadhorse/Prudhoe Bay', 'AK', 51205),
	('PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'AZ', 20896265),
	('TUS', 'Tucson International Airport', 'Tucson', 'AZ', 1594594),
	('IWA', 'Phoenix-Mesa Gateway Airport', 'Mesa', 'AZ', 705731),
	('GCN', 'Grand Canyon National Park Airport', 'Grand Canyon/Tusayan', 'AZ', 319206),
	('1G4', 'Grand Canyon West Airport', 'Peach Springs', 'AZ', 128739),
	('IFP', 'Laughlin-Bullhead International Airport', 'Bullhead City', 'AZ', 109334),
	('NYL', 'Yuma International Airport', 'Yuma', 'AZ', 74742),
	('FLG', 'Flagstaff Pulliam Airport', 'Flagstaff', 'AZ', 64578),
	('LIT', 'Bill and Hillary Clinton National Airport', 'Little Rock', 'AR', 958824),
	('XNA', 'Northwest Arkansas Regional Airport', 'Fayetteville', 'AR', 673810),
	('FSM', 'Fort Smith Regional Airport', 'Fort Smith' , 'AR', 83920),
	('SAN', 'San Diego International Airport', 'San Diego', 'CA', 10340164),
	('OAK', 'Oakland International Airprot', 'Oakland', 'CA', 5934639),
	('SJC', 'Norman Y. Mineta San Jose International Airport', 'San Jose', 'CA', 5321603),
	('SNA', 'John Wayne Airport', 'Santa Ana', 'CA', 5217242),
	('SMF', 'Sacramento International Airport', 'Sacramento', 'CA', 4969366),
	('ONT', 'Ontario International Airport', 'Ontario', 'CA', 2104625),
	('BUR', 'Bob Hope Airport', 'Burbank', 'CA', 2077892),
	('LGB', 'Long Beach Airport', 'Long Beach', 'CA', 1386357),
	('PSP', 'Palm Springs International Airport', 'Palm Springs', 'CA', 995801),
	('FAT', 'Fresno Yosemite International Airport', 'Fresno', 'CA', 761298),
	('SBA', 'Santa Barbara Municipal Airport', 'Santa Barbara', 'CA', 329751),
	('MRY', 'Monterey Regional Airport', 'Monterey', 'CA', 192136),
	('STS', 'Charles M. Schulz-Sonoma County Airport', 'Santa Rosa', 'CA', 167151),
	('SBP', 'San Luis Obispo County Regional Airport', 'San Luis Obispo', 'CA', 162719),
	('BFL', 'Meadows Field', 'Bakersfield', 'CA', 100433),
	('SCK', 'Stockton Metropolitan Airport', 'Stockton', 'CA', 93076),
	('ACV', 'Arcata Airport', 'Arcata/Eureka', 'CA', 69732),
	('COS', 'City of Colorado Springs Municipal Airport', 'Colorado Springs', 'CO', 657694),
	('ASE', 'Aspen-Pitkin County Airport', 'Aspen', 'CO', 254392),
	('GJT', 'Grand Junction Regional Airport', 'Grand Junction', 'CO', 218319),
	('DRO', 'Durango-La Plata County Airport', 'Durango', 'CO', 187789),
	('EGE', 'Eagle County Regional Airport', 'Eagle', 'CO', 163840),
	('MTJ', 'Montrose Regional Airport', 'Montrose', 'CO', 116272),
	('BDL', 'Bradley International Airport', 'Hartford', 'CT', 2982194),
	('XXX',  NULL, 'X', 'DE', 0),
	('MIA', 'Miami International Airport', 'Miami', 'FL', 20875813),
	('MCO', 'Orlando International Airport', 'Orlando', 'FL', 20283541),
	('FLL', 'Fort Lauderdale-Hollywood International Airport', 'Fort Lauderdale', 'FL', 14263270),
	('TPA', 'Tampa International Airport', 'Tampa', 'FL', 9194994),
	('RSW', 'Southwest Florida International Airport', 'Fort Myers', 'FL', 4239261),
	('PBI', 'Palm Beach International Airport', 'West Palm Beach', 'FL', 3100624),
	('JAX', 'Jacksonville International Airport', 'Jacksonville', 'FL', 2729129),
	('SFB', 'Orlando Sanford International Airport', 'Orlando/Sanford', 'FL', 1321675),
	('PIE', 'St. Pete-Clearwater International Airport', 'St. Petersburg/Clearwater', 'FL', 915672),
	('PNS', 'Pensacola International Airport', 'Pensacola', 'FL', 792916),
	('SRQ', 'Sarasota-Bradenton International Airport', 'Sarasota/Bradenton', 'FL', 589860),
	('PGD', 'Punta Gorda Airport', 'Punta Gorda', 'FL', 558482),
	('VPS', 'Destin-Fort Walton Beach Airport', 'Valparaiso', 'FL', 440002),
	('ECP', 'Northwest Florida Beaches International Airport', 'Panama City Beach', 'FL', 434302),
	('EYW', 'Key West International Airport', 'Key West', 'FL', 380505),
	('TLH', 'Tallahassee International Airport', 'Tallahassee', 'FL', 345404),
	('DAB', 'Daytona Beach International Airport', 'Daytona Beach', 'FL', 342495),
	('MLB', 'Orlando Melbourne International Airport', 'Melbourne', 'FL', 220360),
	('GNV', 'Gainesville Regional Airport', 'Gainesville', 'FL', 206330),
	('HNL', 'Daniel K. Inouye International Airport', 'Honolulu', 'HI', 9656340),
	('BOI', 'Boise Airport', 'Boise', 'ID', 1633507),
	('IND', 'Indianapolis International Airport', 'Indianapolis', 'IN', 4216766),
	('DSM', 'Des Moines International Airport', 'Des Moines', 'IA', 1216357),
	('ICT', 'Wichita Dwight D. Eisenhower National Airport', 'Wichita', 'KS', 781944),
	('CVG', 'Cincinnati-Northern Kentucky International Airport', 'Cincinnati/Covington', 'KY', 3269979),
	('MSY', 'Louis Armstrong New Orleans International Airport', 'New Orleans', 'LA', 5569705),
	('PWM', 'Portland International Jetport', 'Portland', 'ME', 886343),
	('BWI', 'Baltimore-Washington International Thurgood Marshall Airport', 'Baltimore/Glen Burnie', 'MD', 12340972),
	('BOS', 'Gen. Edward Lawrence Logan International Airport', 'Boston', 'MA', 17759044),
	('DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit/Romulus', 'MI', 16847135),
	('MSP', 'Minneapolis-St. Paul International Airport', 'Minneapolis', 'MN', 18123844),
	('JAN', 'Jackson-Evers International Airport', 'Jackson', 'MS', 491464),
	('STL', 'St. Louis Lambert International Airport', 'St. Louis', 'MO', 6793076),
	('BZN', 'Bozeman Yellowstone International Airport', 'Bozeman', 'MT', 553245),
	('OMA', 'Eppley Airfield', 'Omaha', 'NE', 2127387),
	('MHT', 'Manchester-Boston Regional Airport', 'Manchester', 'NH', 995403),
	('EWR', 'Newark Liberty International Airport', 'Newark', 'NJ', 19923009),
	('ABQ', 'Albuquerque International Sunport', 'Albuquerque', 'NM', 2341719),
	('FAR', 'Hector International Airport', 'Fargo', 'ND', 402976),
	('CLE', 'Cleveland-Hopkins International Airport', 'Cleveland', 'OH', 4083476),
	('OKC', 'Will Rogers World Airport', 'Oklahoma City', 'OK', 1796473),
	('PDX', 'Portland International Airport', 'Portland', 'OR', 9071154),
	('PHL', 'Philadelphia International Airport', 'Philadelphia', 'PA', 14564419),
	('PVD', 'Theodore Francis Green State Airport', 'Providence/Warwick', 'RI', 1803000),
	('CHS', 'Charleston International Airport', 'Charleston', 'SC', 1811695),
	('FSD', 'Sioux Falls Regional Airport', 'Sioux Falls', 'SD', 510105),
	('BNA', 'Nashville International Airport', 'Nashville', 'TN', 6338517),
	('SLC', 'Salt Lake City International Airport', 'Salt Lake City', 'UT', 11143738),
	('BTV', 'Burlington International Airport', 'Burlington', 'VT', 593311),
	('DCA', 'Ronald Reagan Washington National Airport', 'Washington D.C.', 'VA', 11470854),
	('CRW', 'Yeager Airport', 'Charleston', 'WV', 213412),
	('MKE', 'Milwaukee Mitchell International Airport', 'Milwaukee', 'WI', 3327536);

INSERT INTO Flight (FlightID, AirlineID, DestAirport, FlightDate, PlaneID, AirportID) --MARC (11 airlines, 35 plane models,
VALUES
	(1, 1, 'Hector International Sunport', 2019-02-02, 1, 'BNA'),
	(2, 2, 'Jackson-Evers International Airport', 2019-02-02, 2, 'FSD'),
	(3, 3, 'Ronald Reagan Washingtotn National Airport', 2019-02-02, 3, 'HNL'),										
	(4, 4, 'Gainesville Regional Airport', 2019-02-02, 4, 'CRW'),
	(5, 5, 'Burlington International Airport', 2019-02-02, 5, 'DAB'),
	(6, 6, 'City of Colorado Springs Municipal Airport', 2019-02-02, 6, 'FAT'),
	(7, 7, 'Grand Canyon West Airport', 2019-02-02, 7, 'DSM'),
	(8, 8, 'Indianapolis International Airport', 2019-02-02, 8, 'BET'),
	(9, 9, 'Des Moines International Airport', 2019-02-02, 9, 'DFW'),									
	(10, 10, 'Deadhorse Airport', 2019-02-02, 10, 'SAV'),
	(11, 11, 'Tampa International Airport', 2019-02-02, 11, 'FAI'),
	(12, 1, 'Augusta Regional Airport', 2019-02-02, 12, 'MKW'),
	--and so on up to AT MOST 35 flights because we have 35 plane models being tracked, if this is the right format ill finish this up. Just wanna make sure

INSERT INTO FlightLeg (FlightID, AirlineID, DestAirport, AirportID, LegAirport) --MARC
VALUES
	(8, 8, 'Indianapolis International Airport', 'BET', 1), --I need more clarification as to what the LegAirport value represents

--INSERT INTO Ticket (AccountNo, TicketID, FlightID, AirlineID, DestAirport) --MARC
--VALUES
	

